services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: new
      
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      ConnectionStrings__Default: "Host=host.docker.internal;Database=new;Username=postgres;Password=password"
    depends_on:
      - db
    ports:
      - "8080:80"

volumes:
  pgdata:
